internal/cli/cli.go
internal/command/create/create.go
internal/command/create/gomod.go
internal/command/create/gomod_test.go
livebud/package.json

Changes:
- Fix `bud create` when running minor versions like `go 1.18.1`
- Improves `bud create` in development to automatically link against local packages

bud create fixes and improvements

---

install.sh

If the binary folder is not owned by the user then it fails to install it 
The write permissions of the folder are checked before doing any installing
and elevated permissions are requested for it

fix: installing binary with write permissions

---

internal/gotemplate/gotemplate.go
internal/gotemplate/gotemplate_test.go

This _make sure_ that generate Go files are formatted with [gofmt](https://pkg.go.dev/go/format#Source)
I haven't look at the other files

internal/gotemplate: format (gofmt) on Generate

---

internal/command/create/create.go

Both npm output and the prompt for the app modules is overlapped by each other
Use the original context while prioritizing the prompt and then running the other stuff in the derived context and routines.

fix: move the prompt out of the routines

---

runtime/command/run/run.go

Specifying `127.0.0.1` with the port for the hotServer fixes an issue where a Windows browser was unable to connect to the hotServer running on WSL.
_Full URL `http://127.0.0.1:35729/?page=%2Fbud%2Fview%2Findex.svelte`_

specify 127.0.0.1 for hotServer

---

example/basic/controller/controller.go
package/exe/command.go

When closing a process, interrupt, then kill signals are sent to the process to shut it down.
We weren't handling a class of errors that can pop up. By not handling these errors, we were breaking out of the watch loop and losing live reload.
See this comment for more details: https://github.com/livebud/bud/issues/7#issuecomment-1126956511

ignore interrupt and killed errors when closing a process

---

example/basic/view/index.svelte
internal/bud/bud.go
internal/buildcache/buildcache.go
internal/cli/cli.go
internal/command/build/build.go
internal/command/command.go
internal/command/create/create.go
internal/command/run/run.go
internal/command/tool/cache/cache.go
internal/command/tool/di/di.go
internal/command/tool/v8/client/client.go
internal/command/tool/v8/v8.go
internal/command/version/version.go
runtime/bud/project.go

This PR changes where cached builds are placed:
- From: `$TMPDIR/bud/cache`
- To: `$YOUR_APP/bud/cache`
to fix #27. 
The `./bud/` directory should generally be ignored by source control anyways. If you do choose to vendor the `./bud/` directory, you can always git ignore `./bud/cache/`. You could also run `bud tool cache clean` to remove the `bud/cache` directory.
We may find that this clutters up the project's `bud/` directory too much, but it's better to try and unblock people, then figure out the ideal solution later.
I also hopefully fixed #30 and #46 with https://github.com/livebud/bud/pull/50/commits/b90663032b6f53f140ccaa9242550d9d29cf984e.
This PR is a bit messier than I would have liked, but I took the opportunity to do some additional testing and cleanup. The main changes are …

Move build cache and fallback to copying

---

README.md

This adds a short line to the `README.md` which highlights the recommended `go` version that should be used to run Bud.
I was caught out by #45 too. Please let me know if you have any questions and great job on Bud so far - I've been searching for something like this for a while.

Add comment in README.md about go version

---

Readme.md

Hi @matthewmueller, random gopher here. This project certainly seems to have a bunch of promise!
This PR attempts to capture some of the philosophy of the project that you described elsewhere, but is not currently in the README. 
The text is a slightly cut down version of what you posted to Reddit and Hacker News. (Empirically, that text seems to have been effective 😅 ).
My guess is that with more time, you would probably not use this text exactly (e.g., maybe your style is to not use the first person in a README), but I think having something like this sooner rather than later would be helpful for the project, and then it could be improved later. (And selfishly, I'd like to point some people to this repo, and it would be nice to have more context here).
I also included some pointers to …

readme: add background/philosophy section

---

package/router/radix/tree.go
package/router/radix/tree_test.go
runtime/generator/controller/controller_test.go
runtime/generator/controller/loader.go
runtime/generator/web/loader.go

This PR adds support for custom controller actions like `func (c *Controller) About() { ... }` mapping to `GET /about`. It also fixes a panic when trying to match when there are no routes.
Thanks to @theEyeD's investigation in #67, I was able to add this in a few minutes.
Fixes #54
Closes #67

Add support for custom controller actions

---

runtime/generator/controller/controller.gotext
runtime/generator/controller/controller_test.go
runtime/generator/controller/state.go

Fixes #10 
* Return 204 on `nil` error responses
* Allow void view action by passing empty `map[string]interface{}{}` to view Handler

204 improvements

---

internal/testdir/testdir.go
internal/testdir/testdir_test.go
runtime/generator/program/program.go

Occassionally seeing:
```
Error: error: conjure: generate "bud/.app/program/program.go". program: unable to wire > di: unable to wire "app.com/bud/program".loadApp function. di: unable to find definition for param "app.com/bud/.app/web".*Server in "app.com/bud/.app/command".*Command . parser: unable to find declaration for "app.com/bud/.app/web".Server in "bud/.app/command/command.go". parser: unable to import package "bud/.app/web". conjure: generate "bud/.app/web/web.go". conjure: generate "bud/.app/controller/controller.go". 
parser: unable to import package "controller". controller/controller.go:1:1: expected 'package', found 'EOF'
```
This can happen when you have an empty `controller/controller.go` file. I haven't figured out yet why this occasionally happens.
This test didn't …

internal/testdir: attempt to reproduce occassional EOF error in CI

---

.github/workflows/test.yml
internal/cli/cli.go
internal/cli/testcli/testcli.go
internal/cli/tool/v8/serve/serve.go
internal/extrafile/extrafile.go
internal/extrafile/extrafile_test.go
internal/imhash/imhash.go
package/exe/exe.go
package/js/v8client/client.go
package/js/v8server/server.go
package/js/v8server/server_test.go
package/js/v8server/test-server.go
package/socket/child.go
package/socket/parent.go
runtime/command/run/run.go
runtime/generator/view/view_test.go
scripts/test-slice-pointer/main.go
scripts/test-socket-passthrough/child/main.go
scripts/test-socket-passthrough/main.go
scripts/test-v8-pipe/child/main.go
scripts/test-v8-pipe/grandchild/main.go
scripts/test-v8-pipe/main.go

This PR improves how file descriptors are passed through the system. 
The main goal of this PR was to add support for passing render requests through OS pipes instead of through a spawned bud binary. This makes testing a bit easier.

WIP: V8Pipe support

---

.github/workflows/test.yml

Update CI to use the main branch now after changing it from `bud js v8 client` to `bud js v8 serve`

.github/workflows: update CI to use the main branch

---

.github/workflows/test.yml

Also,
- ci: do not fail fast to preserve error messages
- ci: prefer built-in caching for `actions/setup-go`
- chore: update to the latest gh actions

ci: add matrix testing for supported Go and Node.js versions

---

internal/testdir/testdir.go
runtime/generator/view/view_test.go

Occasionally seeing the following error in CI:
```
error: conjure: generate "bud/.app/main.go". conjure: generate "bud/.app/program/program.go". program: unable to wire. di: unable to wire "app.com/bud/program".loadApp function. di: unable to find module for dependency "app.com/bud/.app/controller".*IndexAction . mod: missing module statement in "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/TestHello4050871875/001/go.mod", received ""
```
It seems like there's a case where `go.mod` is sometimes emptied.

Fix testdir flakiness

---

go.mod
go.sum
package/watcher/watcher.go
package/watcher/watcher_test.go
runtime/command/run/run.go
scripts/test-watcher/main.go

- Dedupe events on linux: stamp each file mentioned in a watch event and compare them with previously seen events
- Improve remove events: sometimes remove events fire before the file has been removed. This was causing the remove function not to trigger. Now we trigger a single remove event regardless whether it's still on disk or not.
- Tighten up tests again: I loosened one of the watch tests to allow for duplicate events to avoid flaky CI. I tightened them up again now that we're deduping.
- Group events within 20ms into a single event with a debounce function: Ideally scaffolding many files should only trigger one change event after all the files have been created.
Closes: https://github.com/livebud/bud/pull/88
Closes: #123

Watch dedupe

---

Makefile
internal/cli/cli.go
internal/cli/create/create.go
internal/cli/create/gomod.go
internal/cli/create/packagejson.go
internal/cli/version/version.go
internal/imhash/imhash.go
internal/testdir/testdir_test.go
internal/versions/versions.go
package/gomod/file.go
runtime/generator/controller/controller_test.go
runtime/generator/view/view_test.go
runtime/view/dom/dom_test.go
runtime/view/ssr/ssr_test.go
scripts/set-package-json/main.go

Closes https://github.com/livebud/bud/issues/125.
Also,
- internal/version: rename package to versions to avoid overlap with the internal/cli/version package.

internal/cli: ensure alignment between CLI and runtime

---

package/commander/commander.go
package/commander/subcommand.go
package/commander/usage.go

Simple internal addition where you can now pass both the root command and subcommands through functions to extend the CLI:
```go
func Extend(cli commander.Command) {
cli = cli.Command("subcommand", "some subcommand")
// ...
}
```

package/commander: support Command interface for both root CLI and subcommands

---

runtime/generator/controller/controller.gotext
runtime/generator/controller/controller_test.go
runtime/generator/controller/loader.go
runtime/generator/controller/state.go

As discussed in #143: if an action matches the `http.HandlerFunc` signature, use it directly. Route parameters are available in `r.URL.Query()`, and a test covers that as well.
Let me know if anything else is needed here!

support HandlerFunc actions

---

runtime/generator/controller/controller_test.go

Add a bit more test to #147 to double-check that other side-by-side actions continue to work as expected.

generator/controller: expand test to ensure other actions continue to work

---

framework/view/loader.go
framework/view/view_test.go
internal/cli/bud/bud_test.go
internal/cli/testcli/testcli.go

After the large refactor #133, I realized that after running `bud build` the embedded client-side scripts were 404ing. This PR fixes that.

framework/view: fix 'bud build' not referencing the correct client-side filepath for hydration.

---

framework/controller/controller_test.go
framework/controller/loader.go

I'm not 100% sure this is the right answer. Imports were needed for params, but all the tests pass without importing results. 
Rather than trying to come up with failing cases, let's just see if anything pops up and we'll then know we need to be more nuanced.
**Update:** looking at the template, the generated code never dives into the result set, so this should work.

framework/controller: don't load imports for action results. closes #137

---

framework/controller/controller_test.go
framework/controller/loader.go

Prior to this PR, controllers couldn't have loaders that could return an error result. This PR fixes that constraint.

framework/controller: support a controller loader with an error result. fixes #101.

---

framework/view/view_test.go

This isn't perfect since it's logged directly to os.Stdout rather than being catchable. 
I'll need to look into PRing https://github.com/kuoruan/v8go-polyfills or bringing it into bud. I also noticed there was no `console.error`, which is unfortunate.

framework/view: test that console.log now works in svelte. closes #87.

---

example/hn/controller/sessions/sessions.go
example/hn/go.mod
example/hn/view/sessions/new.svelte
framework/controller/controller.gotext
framework/controller/controller_test.go
framework/controller/controllerrt/response/response.go
internal/cli/bud/bud.go
internal/cli/cli.go
internal/cli/run/run.go
internal/cli/testcli/testcli.go
internal/cli/toolbs/toolbs.go

This PR will use the `Referer` to redirect back when your form encounters an error during submission. It doesn't return the errors back yet, that will require sessions and flash messages.
Also,
- internal/cli/toolbs: add tool for running bud server so you can run your generated main.go without re-generating the bud/ directory.

framework/controller: add rudimentary redirects on form submissions that have errors

---

contributing/Readme.md

Adds a section on how to run your app without running the generators. This is great for iterating on the generated without working about your changes being overridden by `bud run`.

contributing: add a section to the contributing guide

---

internal/cli/create/create.go
internal/cli/create/create_test.go

`bud create` had a typo where it scaffolded `gitignore` not `.gitignore`. This PR fixes that.

internal/cli/create: fix typo in scaffolding .gitignore

---

framework/transform/transformrt/transform.go

I changed the word "tranform" to the word "transform". I noticed the error while inspecting the code in order to learn more about how the framework works.

fix minor spelling error in output

---

framework/app/loader.go
framework/controller/controller_test.go
framework/controller/loader.go
internal/cli/tooldi/tooldi.go
package/di/di_test.go
package/di/function.go
package/di/hoist.go
package/di/injector.go
package/di/node.go

This PR adds the ability for dependents of external parameters to still be eligible for hoisting.
To understand this PR, consider the following:
**db/db.go**
```go
func Load(ctx context.Context) (*DB, error) {
// ...
}
```
**controller/controller.go**
```go
type Controller struct {
*DB
}
func (c *Controller) Create() (error) {
return c.DB.Exec("...")
}
```
You want to allow passing in an external context, but you don't want to scope the database client to the request. Now the dependency injection framework allows you to do the following (taken from the controller generator):
```go
provider, err := l.injector.Wire(&di.Function{
Name:    fnName,
Target:  l.module.Import("bud", "controller"),
Imports: l.imports,
Hoist:   true,
Results: []di.Dependency{
&di.Type{
Import: importPath,
Type: …
```

package/di: Add Hoist option for dependents of external parameters to still be eligible for hoisting

---

Makefile

A slightly better approach would be to modify:
https://github.com/livebud/bud/blob/3a251081b908bc8c2dd15cfcaac0352b03e59f82/internal/urlx/parse.go#L13
To use `go run github.com/pointlander/peg`, but currently it generates a header comment that would change every time.
E.g.
```
// Code generated by /var/folders/4f/tcxcr6_55v9bp38d8g4hjlf80000gn/T/go-build1073813380/b001/exe/peg
```

makefile: add tools to install script. closes #215

---

Makefile

Fixes:
```
go install github.com/livebud/bud@
go install: github.com/livebud/bud@: version must not be empty
```
In: https://github.com/livebud/bud/runs/7479494559?check_suite_focus=true

makefile: GITHUB_HEAD_REF is empty when running on main branch, so default to main

---

Makefile

Seems like Go Proxy or Go Sumdb can't keep up or something. Use `GOPRIVATE` to reduce chances.

Fix e2e on main

---

framework/generator/generator_test.go
internal/cli/run/run.go
internal/cli/testcli/testcli.go
internal/pubsub/pubsub_test.go

This is a follow-up to #236 where generators are re-run upon change.

internal/cli/run: Remove extra app:ready events that were firing too early

---

internal/cli/create/create.go
internal/cli/create/create_test.go

Auto infer module when `bud create` outside $GOPATH

---

internal/cli/toolfsls/toolfsls.go
internal/cli/toolfstxtar/toolfstxtar.go

Prior to this PR, `-C` was ignored for the following commands
```sh
bud -C example/basic tool fs ls
bud -C example/basic tool fs txtar
```
Now it's respected. Discovered this while working on #244.

internal/cli/tool*: support -C chdir support

---

framework/app/app_test.go
internal/cli/run/run.go
package/socket/socket.go
package/socket/socket_test.go

This PR replaces https://github.com/livebud/bud/pull/261. That PR didn't have the push permissions. This PR moves the increment logic into a new method in socket called ListenUp. This makes testing this change quite a bit easier.
Closes: #250 
Unfortunately it's not a complete solution if you have `--hot` enabled (defaults to true with `bud run`):
```sh
bud run
| Listening on http://127.0.0.1:3001
| listen tcp 127.0.0.1:35729: bind: address already in use
```
But it will work if you have another type of server running on port 3000 (e.g. Rails or Next.js)
Keep an eye on https://github.com/livebud/bud/issues/251 for a complete solution.

+1 to port if necessary

---

Makefile
contributing/Readme.md

Minor improvement to make it easier to contribute by adding a default target to the `Makefile` so that `make` sets up Bud for contributions.

Makefile: default to install when running 'make'. Closes: #265

---

framework/controller/controller_test.go
internal/is/is.go
internal/is/is_test.go
package/budfs/budfs.go

Additionally, 
- `internal/is`: add NotIn function
- `package/budfs`: use cached filesystem when syncing.

framework/controller: add create, update, delete file tests

---

example/hn/go.sum
framework/app/app.gotext
framework/framework.go
framework/generator/generator.go
framework/generator/generator.gotext
framework/generator/generator_test.go
framework/generator/loader.go
framework/generator/state.go
internal/cli/bud/bud.go
internal/cli/build/build.go
internal/cli/run/run.go
internal/cli/toolbs/toolbs.go
internal/cli/toolfscat/toolfscat.go
internal/cli/toolfsls/toolfsls.go
internal/cli/toolfstxtar/toolfstxtar.go
internal/gobuild/gobuild.go
internal/prompter/prompter.go
package/budfs/budfs.go
package/budfs/budfs_test.go
package/budfs/treefs/treefs.go
package/budfs/treefs/treefs_test.go
package/remotefs/command.go
package/virtual/exclude.go
package/virtual/exclude_test.go
package/virtual/print.go

This PR adds support for custom generators. Custom generators allow you to define application-specific code generators that hook into the rest of the code generators. There was a first attempt at doing this in https://github.com/livebud/bud/pull/236, but it was subsequently removed in https://github.com/livebud/bud/pull/276 because the implementation had some tradeoffs so I looked for a better solution.
You can add a custom generator to you application by creating packages inside the `generator/` directory. For example, you can define the following package in `generator/tailwind/tailwind.go`
```go
package tailwind
import (
"github.com/livebud/bud/package/budfs"
)
type Generator struct {
// Dependencies
}
func (g *Generator) GenerateDir(fsys budfs.FS, dir *budfs.Dir) error { …
```

Add support for custom generators

---

framework/controller/controller_test.go
framework/generator/generator_test.go
framework/view/view_test.go

Watching files in CI is still a bit flaky, so this allows the test to fail sooner.

Add more test timeouts

---

internal/cli/cli.go
internal/cli/toolfstree/toolfstree.go
internal/printfs/printfs.go

This PR adds the `bud tool fs tree` CLI subcommand. This command is helpful for getting an overview of the virtual file system's structure.
For example,
```sh
$ bud tool fs tree bud/
bud
└── internal
├── app
│   ├── controller
│   │   └── controller.go
│   ├── main.go
│   ├── public
│   │   └── public.go
│   ├── view
│   │   └── view.go
│   └── web
│       └── web.go
└── generator
└── tailwind
```

Add 'bud tool fs tree [dir]' command

---

package/budfs/budfs.go
package/budfs/budfs_test.go
package/budfs/treefs/treefs.go
package/remotefs/client.go
package/remotefs/remotefs_test.go

Adds a `Mount` function to the bud filesystem. This will be used to better support application-specific generators.
This PR also fixes two internal bugs:
1. treefs: Root files should be checked for existence when running fs.ReadDir
2. remotefs: trying to read a non-existence real file (via os) should return an error that wraps `fs.ErrNotExist`.

package/budfs: add mount and fix a few bugs

---

framework/view/dom/dom.go
framework/view/ssr/ssr.go
package/budfs/budfs.go
package/budfs/budfs_test.go

This PR changes the name from fsys.Link to fsys.Watch.
Additionally,
- Add support for passing in multiple paths at once.
- Add support for watching glob patterns.
- This also improves reactivity on single files.

package/budfs: switch from fsys.Link to fsys.Watch

---

framework/controller/controller.go
framework/generator/generator.go
internal/dsync/dsync.go
internal/dsync/dsync_test.go
package/budfs/budfs_test.go
package/budfs/treefs/fillerdir.go
package/budfs/treefs/treefs.go
package/budfs/treefs/treefs_test.go
package/virtual/vcache/memory_test.go
package/virtual/vcache/wrap.go

Prior to this PR, if you had a file generator at `bud/controller/controller.go` and you read the directory of `bud/controller`, it would run the generator for `bud/controller/controller.go`. Now reading a directory no longer runs the generator.
This makes it easier to have generators that depend on their subdirectories. This also seems like what you'd expect (why is the parent calling my generator?) and should also make when generators run a bit more predictable. 
There's a tradeoff here though. Now if you have:
```go
bfs.FileGenerator("bud/controller/controller.go", func(fsys budfs.FS, file *budfs.File) error {
return nil, fs.ErrNotExist
})
```
And you read the `bud/controller` it will report 1 file, `controller.go`, but then when you go and read that file, it will say it doesn't exist. …

package/budfs: reading the parent directory no longer triggers file generator

---

framework/generator/generator.go
internal/cli/bud/bud.go

Internal prep work. 
Currently when you define generators, they all land in `bud/internal/generator/...`. This limits their discoverability by the other generators. This is the first step in allowing you to define generators anywhere.

framework/generator: mount generators from the root for more flexibility

---

framework/generator/generator.go
framework/generator/generator.gotext
framework/generator/generator_test.go
framework/generator/loader.go
internal/bfs/bfs.go
internal/cli/bud/bud.go
internal/cli/build/build.go
internal/cli/run/run.go
internal/cli/toolbs/toolbs.go
internal/cli/toolfscat/toolfscat.go
internal/cli/toolfsls/toolfsls.go
internal/cli/toolfstree/toolfstree.go
internal/cli/toolfstxtar/toolfstxtar.go
package/budfs/budfs.go
package/budfs/budfs_test.go
package/finder/finder.go

Follow-up to: https://github.com/livebud/bud/pull/296
Generators can now generate anywhere. For example, you can define a generator in `generator/tailwind`:
```go
package tailwind
import (
"github.com/livebud/bud/package/budfs"
)
type Generator struct {
Compiler *tailwind.Compiler
}
func (g *Generator) Register(dir *budfs.Dir) {
dir.GenerateFile("bud/internal/tailwind/tailwind.go", func(fsys budfs.FS, file *budfs.File) error {
file.Data = []byte("package tailwind\n// compiled tailwind")
return nil
})
}
```

framework/generator: expand capabilities of generators with a generator.Register

---

framework/app/loader.go
framework/view/viewrt/viewrt.go
package/budhttp/budsvr/server.go
package/budhttp/client.go
package/budhttp/client_test.go
package/budhttp/discard.go

This PR is prep work for https://github.com/livebud/bud/pull/300.
`budhttp.Client` is now a bit more low-level, implementing `js.VM` and `fs.FS` instead of being a renderer. This reduces the differences between the embedded and live views, so we can simplify the view runtime.

budhttp: budhttp.Client implements js.VM

---

framework/app/loader.go
framework/controller/loader.go
framework/public/public_test.go
framework/view/view_test.go
framework/web/loader.go
framework/web/web.go
framework/web/web_test.go
internal/bfs/bfs.go
internal/gitignore/gitignore_test.go
internal/glob/compile_test.go
package/budfs/budfs_test.go

This PR allows custom generators to be picked up by the existing web generator and pulled in. This will be a low-level solution for middleware and custom routing. 
Still working out the details, but after this PR, you'll be able to define a generator in `bud/internal/web` with a certain API and the web generator will include that in its web server code.

framework/web: support custom web generators

---

internal/dsync/dsync.go
internal/dsync/dsync_test.go
package/budfs/budfs_test.go

As part of the tradeoff made in https://github.com/livebud/bud/pull/293, `fs.ReadDir` no longer stats each directory entry to see if it exists. 
This leads to previously existing generators not being deleted when they return `fs.ErrNotExist`. 
This PR fixes dsync to cleanup those files that no longer exist.

internal/dsync: fix bug where generators were not being deleted when returning fs.ErrNotExist

---

package/router/radix/tree.go
package/router/radix/tree_test.go
package/router/router.go
package/router/router_test.go

This PR allows the router to define routes that are uppercase, but get converted into case-insensitive routes when inserted into the radix tree.
Additionally, instead of erroring out on trailing slashes, we trim trailing slashes. 
Finally, instead of redirecting trailing slashes to the non-trailing slash variant, we'll expect folks to use the canonical meta tag to avoid distinct pages of the same content showing up in their analytics.
The reason for doing this now is to expose the chunk names in ESBuild which use a hash of uppercase characters.

Relax router inputs and remove automatic redirects.

---

go.mod
go.sum
package/trpipe/trpipe.go
package/trpipe/trpipe_test.go

This package will be used by the transformer to create a pipeline of transforms, allowing you to transform from .md => .svelte => .js
It's not currently exposed yet, but I'm adding it to bud so it can be iterated on in place.

package/trpipe: add initial trpipe for creating a pipeline of transformations

---

internal/cli/cli.go
internal/cli/generate/generate.go

This PR adds a `bud generate` command. This command is almost exactly the same as `bud build` except it:
- uses the development flag defaults instead of the production flag defaults
- doesn't run `go build` at the end
- runs `go generate [args]` if there are arguments passed through

add 'bud generate' command

---

internal/cli/cli.go
internal/cli/tooldi/tooldi.go

Two small fixes for `bud tool di`

bud tool di: add name support. only use inject files that exist in the filesystem

---

framework/generator/loader.go
framework/transform2/loader.go
framework/transform2/state.go
framework/transform2/transform.go
framework/transform2/transform.gotext
framework/transform2/transform_test.go
framework/transform2/transformrt/transformrt.go
internal/bfs/bfs.go

This PR is a follow-up to: https://github.com/livebud/bud/pull/288
This PR creates a "transform service" that you can add custom transforms to that can be used by other generators. The goal of this PR is to:
- Decouple transforms from generators and allow developers to bring their own transforms
This will enable:
- Custom views (e.g. index.md)
- Transpiler support (e.g. expanding tailwind classes to CSS)
- Custom imports (e.g. `import svgPath from "./something.svg"`)
- Static file transforms (e.g. minifying svgs using svgo)
The idea being that the public generator can request a file through the transform service:
```go
code, err := fs.ReadFile(fsys, "bud/service/transform/svg/public/favicon.svg")
```
And if there's an `IcoToIco` transform enabled, this favicon will pass through the .ico …

framework/transform2: add initial internal transform service support

---

framework/app/app_test.go
framework/controller/controller.gotext
framework/controller/loader.go
framework/web/loader.go
framework/web/state.go
framework/web/web.gotext
framework/web/welcome/welcome.go

This is the final part of https://github.com/livebud/bud/pull/309
The generated controller now contributes routes to the web generator. By abstracting out the web generator, you'll be able to contribute other routes to the web generator.

framework/{controller,web}: register routes from within the controller

---

framework/transform2/transform.gotext
framework/transform2/transformrt/transformrt.go
internal/errs/errs.go
internal/errs/errs_test.go

Two minor changes while working on custom views:
- internal/errs: fix error chaining. 
- framework/transform2: remove unused state

internal/errs: fix error chaining. 

---

internal/glob/compile.go
internal/glob/compile_test.go

This fixes an issue where a pattern like `{a,b/*/**.go}`, would match on `b/main.go`. Now it won't match on `b/main.go`, but will match on `b/b/main.go` and `b/b/b/main.go`, etc.
More context in this issue: https://github.com/gobwas/glob/issues/50

internal/glob: fix wildcards in multi-select

---

install.sh

This PR removes an unnecessary failure mode in the install script. 
Thanks to @chriswalz for reporting this and confirming the fix.

install.sh: remove GITHUB_TOKEN usage in install.sh. Fixes: #348

---

contributing/Readme.md
framework/generator/loader.go
internal/cli/cli_test.go
internal/cli/generate.go
internal/cli/tool_v8_test.go

Small cleanup to move the generated app's main.go file from `bud/internal/app/main.go` to `bud/cmd/app/main.go`

move app from bud/internal/app to bud/cmd/app

---

framework/public/public_test.go
internal/cli/create_test.go
internal/cli/new_controller_test.go
internal/cli/run.go
internal/dag/sqlite.go
internal/embedded/gitignore.txt
internal/gitignore/gitignore.go
internal/testcli/testcli.go

This PR makes a few changes to make `bud run` more tolerable to errors.
The big one was always ignoring the `bud` directory during `bud run` regardless of if there's a `.gitignore` or not. This alone greatly reduced the number of rebuilds triggered (and likely sped up reloads too!).
I also fixed an issue where if you remove the bud directory entirely during `bud run`, it will now exit more gracefully.
I still think there are ways to end up in weird run states if you're able to kick off multiple generates concurrently. One way to do this would be to have two bud run processes going.
To deal with generates racing, bud's generate should lock to allow only one generate to go at a time. I think we can do this in the `bud/bud.db` SQLite database.

improve 'bud run' tolerance to errors

---

internal/cli/create.go
internal/cli/create_test.go

Adds the missing `v` prefix that `go.mod` expects.

internal/cli: fix bud create and add a test. fixes: #360

---

framework/generator/generator.go
framework/generator/generator.gotext
framework/generator/generator_test.go
framework/generator/loader.go
framework/generator/state.go
internal/cli/cli.go
internal/testcli/testcli.go
package/remotefs/client.go

Hidden in the `v0.2.6` release is custom generator support. I didn't mention it because the API wasn't stable. In this PR, I take another pass over the custom generator API. I'm feeling pretty good about it now.
The important thing to note is that the custom code generators that you'd write for your application are equally as powerful as the code generators that Bud ships with. The benefit of writing custom generators within the framework is that you get caching, depending on other generators and hot reload for free.
For example, if you add the following code in the `$APP/generator/graphql` package:
```go
package graphql
import "github.com/livebud/bud/package/genfs"
type Generator struct {
// Add dependencies here to load them in via dependency injection
}
func (g *Generator) …
```

framework/generator: updated the custom generator api

---

Makefile
internal/cli/create_test.go

This test was added to fix https://github.com/livebud/bud/pull/361, but that's causing failures on non-releases. Now we'll run this test only during the publishing process and skip it every other time.

make: fix tests for non-release PRs

---

package/di/di_test.go
package/di/finder.go
package/di/function.go
package/parser/alias.go
package/parser/definition.go
package/parser/file.go
package/parser/package.go
package/parser/typespec.go

This PR adds support for dependency injection with custom types.  For example, if you wanted to provide `*View` in the following example:
```go
func LoadPages() (Pages, error) {
return Pages{"index.svelte", "frame.svelte"}, nil
}
type Pages []string
func Load(pages Pages) *View {
return &View{pages}
}
type View struct {
pages Pages
}
```
The generated code would look something like:
```go
// Generated. Do not edit
func load() (*View, error) {
pages, err := LoadPages()
if err != nil {
return nil, err
}
view := Load(pages)
return view, nil
}
```
Custom types do not try to initialize themselves (e.g. `Pages{}`). They need to be initialized with a function, so if `LoadPages` 
wasn't present, `di` would return an error. 
I originally tried passing the empty value through, but it was just too …

package/{di,parser}: add typespec support

---

package/esb/esb.go
package/esb/esb_test.go

This PR adds the `esb` (short for esbuild) package to Bud. The purpose of this package is to provide common presets that viewers can use and extend in #383. 
I'm also taking this opportunity to try and move esbuild fully to a virtual filesystem, so it's much easier to test different combos.

package/esb: initial esbuild package rewrite

---

framework/afs/afsrt/appfsrt.go
framework/app/app.gotext
internal/cli/create.go
internal/cli/run.go
internal/dsync/dsync.go
package/log/console/console.go
package/log/console/console_test.go
package/log/discard.go
package/log/log.go
package/log/memory/memory_test.go

This PR changes the internal logger API to be more familiar:
Before:
- `Info(msg, args ...interface{})` behaved like `fmt.Sprintf` (with a newline)
Now:
- `Info(msg, args ...interface{})` behaves like `fmt.Println`
- `Infof(msg, args ...interface{})` behaves like `fmt.Sprintf` (with a newline)

Improve log

---

.envrc
.tool-versions

As [promised](https://github.com/livebud/bud/pull/381#issuecomment-1437730820), this PR adds support for `direnv` to work together with `asdf` seamlessly.
To make use of it, [direnv](https://direnv.net/) and [asdf-direnv](https://github.com/asdf-community/asdf-direnv) should be set up.

build: add `direnv` support

---

.envrc
.tool-versions

In reply to the [last PR](https://github.com/livebud/bud/pull/393#issuecomment-1477270170):
> Hmm... just tried it. Getting:
> 
> ```
> direnv: loading ~/dev/src/github.com/livebud/bud/.envrc                                                        
> direnv: using asdf
> /bin/bash:1033: use_asdf: command not found
> ```
> 
> Sorry, I should have been a bit more clear. Basically, I'd like this to support the following matrix:
> 
> * no direnv, no asdf, no problem
> * direnv, no asdf, no problem
> * asdf, no direnv, no problem
> * asdf, direnv, yayyyy
> 
> Reverting for now, but happy to merge once this is sorted.
Oh i c,  `asdf` seemed to be present, but `asdf-direnv` wasn't installed / set  up. So this player should be added to the matrix as well ;)
* no asdf, no direnv, no asdf-direnv, no …

build: add `direnv` support and integrate with `asdf`
