- internal/testdir/testdir_test.go
Skip it for now since I'll be reworking the tests soon anyway
> internal/testdir: this test currently fails in CI. 

- Makefile
- install.sh
> makefile,install.sh: use a path with the version number in it

- runtime/command/new/controller/controller.go
- runtime/command/new/controller/view/index.gotext
- runtime/command/new/controller/view/show.gotext
> runtime/command/new/controller: Fix links when generating controllers and views

- internal/bail/bail.go
- internal/cli/cli.go
- internal/generator/command/command.gotext
- package/di/finder.go
- package/gomod/mod.go
- package/gomod/mod_test.go
A few minor changes while prepping v8 client pipe:
- make generator more resilient
- adjust error formatting
- return missing error
> make generator more resilient, adjust error formatting, return missing error

- contributing/Readme.md
Update contributing guide based on CI results.
> update contributing guide

- internal/current/current.go
- internal/current/current_test.go
`current.Directory()` wasn't working correctly. Fixed that and added tests.
> internal/current: fix current package and add tests

- internal/cli/cli.go
In #126, we missed the case where the module wasn't downloaded yet. This PR fixes that.
> internal/cli: download runtime if we upgrade it

- package/di/di_test.go
These got lost somewhere in git. This PR adds them back in.
> package/di: add back the long lost dependency injection tests

- internal/imhash/imhash.go
- internal/imhash/imhash_test.go
I needed glob support for embedding migrations (`*.sql`) so here ya go! Feedback welcome as always. ✌️
> support glob embeds

- Readme.md
- internal/cli/bud/bud.go
- package/watcher/watcher.go
- package/watcher/watcher_test.go
I wanted to test the upcoming v0.1.9 bud release against @vito's [Bass Loop](https://github.com/vito/bass-loop/discussions/1).
The following commits are some fixes thanks to Bass Loop.
> Fixes and additions thanks to Bass Loop

- internal/cli/bud/bud.go
In 0b976efe493382bdc2459b84e364b11807a5a9e9, there was an attempt to download the latest runtime when we're on the development version of bud. This was triggering a lot of extra downloading in CI. 
Now we just a try a best effort attempt at loading a local runtime. If it falls, the go.mod is unchanged and you'll need to manually adjust the runtime if there were breaking changes in between CLIs. The runtime will stabilize over time, so this will be less and less of a problem over time too.
> internal/cli: try replacing on latest, rather than downloading.

- framework/controller/controller_test.go
The fix was actually made in #133, but this adds a test for it.
> framework/controller: test that we can pass custom env vars through bud run. closes #151.

- framework/app/app.gotext
- framework/app/loader.go
- framework/app/state.go
> framework/app: embed an empty go.mod to fix self-contained built app.

- internal/bail/bail.go
- internal/cli/create/create.go
- internal/cli/create/create_test.go
> internal/cli/create: fix scaffolding when outside of $GOPATH.

- Readme.md
- framework/controller/controller_test.go
- install.sh
- internal/fscache/fscache.go
- internal/fscache/wrap.go
- internal/fscache/wrap_test.go
- package/overlay/overlay.go
- [readme: remove $ for better copy pastability](https://github.com/livebud/bud/commit/df0e4bd6354ebb6a65663bebb51badab7c172773)
- [install.sh: support passing a version as an environment variable](https://github.com/livebud/bud/commit/db0635d27cfbb47e3421992f6c6044c409fbadf9)
- [fscache: clear all caches between runs.](https://github.com/livebud/bud/commit/543ed72ee09b87d94f51ac54a0a2fe218be91a86)
> Various improvements

- framework/controller/controller_test.go
- framework/controller/controllerrt/request/unmarshal_test.go
- framework/controller/loader.go
I had some leftover todos to check after writing the docs that I wanted to write tests for.
> framework/controller: add some missing tests based on documentation

- internal/cli/create/create.go
I originally wanted to write to tempdir because I didn't want failures to result in half built directories. Since folks are [running into problems](https://github.com/livebud/bud/pull/167#issuecomment-1168279700), I think its worth revisiting this. 
This PR will now just write into the intended directory.
> internal/cli: write to dir instead of temp

- Readme.md
- internal/cli/bud/bud.go
- internal/cli/bud/bud_test.go
- internal/cli/cli.go
> internal/cli: ensure the developer's version of Go is new enough for Bud

- internal/cli/newcontroller/view_edit.gotext
Minor tweaks to avoid prettier from re-formatting it.
> internal/cli/newcontroller: fix edit view to make prettier happy

- example/basic/view/edit.svelte
- framework/view/view_test.go
- internal/cli/run/run.go
- internal/prompter/prompter.go
- package/watcher/watcher.go
- package/watcher/watcher_test.go
This PR fixes reload support when you add or change files. Much thanks to @dangerzone for kicking this fix off!
Closes: #138
Closes: #197
> Recompile triggers

- framework/view/view_test.go
- internal/sig/sig_test.go
- package/hot/hot_test.go
Try fixing flaky view test that are cropping up more frequently.
> framework/view: try not using td.Write a second time to fix tests

- framework/controller/controller_test.go
Aims to fix: https://github.com/livebud/bud/runs/7383313044?check_suite_focus=true
> framework/controller: manually write files to reduce flakiness in CI

- internal/cli/create/create.go
- internal/cli/create/create_test.go
Allows for Bud's code to be in a directory with spaces.
Closes #216
> internal/cli/create: add autoquote to modfile replaces. closes #216

- framework/app/loader.go
- framework/controller/loader.go
- framework/view/viewrt/viewrt.go
- scripts/test-watcher/main.go
Removing code that's no longer in use. This is prep work for improving the view support.
> framework/app: remove unused aliases

- .gitignore
- Makefile
- framework/view/ssr/svelte.js
- package/svelte/compiler.js
> gitignore: commit bundled js files to avoid errors in bud runtime package

- Makefile
This is an attempt to fix the E2E test for #242
> makefile: attempt to fix e2e

- Makefile
- framework/controller/controllerrt/request/unmarshal.go
- framework/web/welcome/welcome.go
- go.mod
- go.sum
- internal/cli/testcli/testcli.go
- internal/cli/toolv8/toolv8.go
- internal/dsync/set/set.go
- internal/golden/golden.go
- internal/is/is_internal.go
- internal/is/is_test.go
- internal/snapshot/snapshot.go
- internal/testdir/testdir.go
- internal/testdir/testdir_test.go
- package/budfs/genfs/genfs_test.go
- package/budfs/treefs/treefs.go
- package/commander/subcommand.go
- package/di/di_test.go
- package/di/finder.go
- package/gomod/file.go
- package/hot/client.go
- package/modcache/modcache.go
- package/remotefs/client.go
- package/router/lex/lex.go
- package/router/radix/tree_test.go
- package/router/router_test.go
- package/socket/socket_test.go
- package/vfs/singleflight.go
- package/watcher/watcher.go
- tools.go
Since my IDE has [staticcheck](https://staticcheck.io) built-in I would occasionally fix issues in the specific files, but this PR fixes the existing staticcheck issues and now runs staticcheck in CI and reports any issues across the entire codebase.
> Fix staticcheck issues and add staticcheck to ci

- framework/view/view_test.go
There should be no restrictions on where you can import from. This PR tests that.
This PR was kicked off by @JanGordon (thank you!)
Closes #280.
> framework/view: add test to confirm desired relative path behavior for views

- package/budfs/budfs_test.go
- package/budfs/linkmap/linkmap_test.go
Add a quick test to validate behavior
> add budfs exclude test

- internal/dag/dag.go
- package/budfs/budfs_test.go
Quick test in prep for transform PR
> internal/dag: remove cycle check and test that cycles are no longer a problem

- framework/generator/generator.go
- framework/generator/loader.go
- internal/bfs/bfs.go
> framework/generator: minor cleanup

- package/finder/finder.go
> package/finder: check that the file exists (by running generator)

- package/di/di_test.go
- package/di/function.go
- package/di/node.go
While working on refactoring the web generator, this issue popped up. Now you can pass interfaces through as parameters into DI.
> package/di: support interface params

- framework/view/view_test.go
Improve test coverage for views in preparation for the refactor
> framework/view: better test coverage for views

- internal/imhash/imhash.go
Tiny error improvement that will save some debugging time.
> internal/imhash: improve imhash error

- framework/public/public_test.go
- package/socket/socket_test.go
Fixed 2 test that were occasionally failing.
> fix intermittently failing tests

- framework/app/app.gotext
- framework/app/loader.go
- framework/generator/generator.gotext
- framework/generator/loader.go
- internal/cli/bud/bud.go
- package/log/console/console.go
- package/log/console/console_test.go
- package/log/levelfilter/levelfilter.go
- package/log/log.go
- package/log/memory/memory_test.go
- package/log/testlog/testlog.go
This should be configurable after initialization.
> package/log: remove global level filter

- framework/app/app.gotext
- internal/cli/run/run.go
- internal/cli/testcli/testcli.go
- package/budfs/budfs.go
- package/budfs/linkmap/linkmap.go
- package/budhttp/budsvr/server.go
- package/di/di.go
- package/di/finder.go
- package/di/function.go
- package/di/injector.go
- package/di/node.go
- package/di/struct.go
- package/hot/server.go
- package/trpipe/trpipe.go
- package/virtual/vcache/wrap.go
After recently updating the structured logger, the debug logs were missed. This PR fixes the debug logging.
> misc: fix debug logs

- framework/transform2/transformrt/transformrt.go
- package/gomod/mod.go
- package/gomod/mod_test.go
- package/trpipe/trpipe.go
Some small changes to prep for introducing viewers.
> Viewer prep

- internal/bfs/bfs.go
- internal/cli/generate/generate.go
The main purpose of this PR is to make it easier to debug specific code generators because you can run each code generator individually. 
For example, you can now generate just the `view` and `controller` generator with:
```sh
bud generate bud/internal/web/view bud/internal/web/controller
```
This should encourage the generators that are developed to be more useful as standalone packages.
This PR also removed auto-calling `go generate ./...`. Since I haven't released a new version since adding bud generate, I'm taking the liberty to make this change now. 
I might add it back in with a better use case, but for now, I think bud generate and go generate should be considered different commands that do different things.
> cli/generate: 'bud generate bud/paths' will now run specific code generators

- internal/once/closer.go
- internal/once/closer_test.go
- package/budfs/budfs.go
- package/remotefs/command.go
> once/closer: refactor api

- internal/cli/run/run.go
- package/remotefs/remotefs_test.go
- package/virtual/vcache/mock.go
Miscellaneous fixes spawned from the add/afs branch.
> misc: add mock cache, fix remotefs test and run log

- internal/cli/cli.go
- internal/cli/create/create.go
- internal/cli/run/run.go
- internal/versions/align.go
- internal/versions/align_test.go
- internal/versions/check.go
- internal/versions/check_test.go
- package/gomod/mod.go
Moves a few utility functions into more appropriate packages. This was pull out of a larger refactor.
> Move utils

- framework/public/public_test.go
> framework/public: try increasing the timeout for ci and add comment

- contributing/Readme.md
Add link to "good first issue".
> misc: Update link in contributing

- example/hn/go.sum
- framework/app/loader.go
- framework/public/loader.go
- framework/public/public_test.go
- internal/testcli/process.go
- internal/testcli/testcli.go
- runtime/transpiler/transpiler.go
This PR integrates transpiler support into public.
The main use case I have in mind here is running image compression on public files before embedding them.
> public: integrate transpiler support into public

- go.mod
- go.sum
- package/di/di_test.go
- package/parser/parser_test.go
> bump transpiler

- package/budhttp/client.go
- package/budhttp/client_test.go
- package/budhttp/discard.go
This command has been moved to the application file server (afs)
> budhttp: remove no longer used Open command

- .envrc
- .tool-versions
> Revert "build: add `direnv` support"

- go.mod
- go.sum
- package/middleware/httpbuffer/middleware.go
- package/middleware/httpbuffer/middleware_test.go
Adds a httpbuffer package needed for session support
> add httpbuffer middleware
